queirozcamila/minhafeira

- app/controllers/products_controller.rb
- test/controllers/products_controller_test.rb
Por favor revisem o products controller
> Add products controller

- app/controllers/products_controller.rb
Criamos o redirect das ações para a pagina do shop
> Created redirect_to when create and update

- app/controllers/products_controller.rb
- app/controllers/shops_controller.rb
Criação do shops controller, por favor revisem
> Created shops controller

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
> User controller

- config/routes.rb
> Created all routes

- app/controllers/application_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/shops/index.html.erb
- test/controllers/carts_controller_test.rb
transferir a home page para shop#index, verificar!
> Shops views

- app/controllers/application_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- test/controllers/carts_controller_test.rb
criado carts_controller, favor revisar!
> Carts controller

- app/views/shops/new.html.erb
html para formulário de cadastro de shop.
@gustborges @patriciachedid @queirozcamila podem validar dps? não mexi em estilo ainda. só fiz o formulario e testei se criou certinho a instance variable
> make view shops new

- app/views/shops/edit.html.erb
formulario para edição de shop.
@queirozcamila
> create view shop edit

- app/controllers/shops_controller.rb
- app/views/shops/edit.html.erb
editei o before_action, estava faltando o update. Ai estava quebrando a pagina.
@queirozcamila
> Fix shop controller update

- app/views/shops/show.html.erb
inseri o botao para deletar e fiz a validação do destroy.
@queirozcamila
> test destroy and insert delete btn

- app/controllers/shops_controller.rb
- app/policies/shop_policy.rb
- test/policies/shop_policy_test.rb
Coloquei o pundit no controller do shops e inseri o file do shop-policy. Não fiz nada com a view.
> Adding pundit on shops controller and shop_policy

- app/controllers/cart_products_controller.rb
- test/controllers/cart_products_controller_test.rb
> Cart products controller

- app/controllers/application_controller.rb
- app/controllers/cart_products_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/shops_controller.rb
- app/views/pages/home.html.erb
- test/controllers/shops_controller_test.rb
Adicionei o skip_before_action em algumas funções dos controllers.
> Adjusted skip_before_action to controllers

- app/controllers/shops_controller.rb
- app/policies/shop_policy.rb
> Adjusts shops pundit

- app/controllers/shops_controller.rb
> fixes shop index

- app/controllers/cart_products_controller.rb
- app/policies/cart_policy.rb
- app/policies/cart_product_policy.rb
- app/policies/product_policy.rb
- test/policies/cart_policy_test.rb
- test/policies/cart_product_policy_test.rb
- test/policies/product_policy_test.rb
> created policies

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/seeds.rb
please merge 
had to do some minor changes in the models
> adding shops seeds

- app/views/shared/_form.html.erb
- app/views/shops/edit.html.erb
- app/views/shops/new.html.erb
Joguei o formulário num partial e coloquei um render nos views
> Created a partial for form

- db/migrate/20200508124628_add_admin_to_users.rb
- db/schema.rb
Pessoal, adicionei o admin no users para o authorization
> Added an admin column on users table

- app/models/product.rb
- app/models/shop.rb
- db/seeds.rb
please merge latter 
had to do some minor changes in the models
> adding products seeds

- app/views/shops/edit.html.erb
- app/views/shops/index.html.erb
- app/views/shops/new.html.erb
- app/views/shops/show.html.erb
Pessoal, adicionei uns links no view do shops
> Added some links on shops view - index and show

- app/views/shops/edit.html.erb
- app/views/shops/index.html.erb
- app/views/shops/new.html.erb
- app/views/shops/show.html.erb
Reverts queirozcamila/minhafeira#24
> Revert "Added some links on shops view - index and show"

- app/controllers/products_controller.rb
- app/policies/product_policy.rb
- app/views/products/edit.html.erb
- app/views/products/index.html.erb
- app/views/products/new.html.erb
- app/views/shops/new.html.erb
- app/views/shops/show.html.erb
pessoal, fiz uma branch para os views e acertos nos controllers e policies dos products. Aqui funcionou tudo. podem validar? são varios commits em uma branch mesmo.
@gustborges @queirozcamila @patriciachedid
> Prodct view

- app/views/shops/index.html.erb
Pessoal, tentei fazer um card slider com os cards dos shops na home. Tem muito front ainda pra ajeitar aqui
> Adicionando cards slider na home

- app/views/products/new.html.erb
- app/views/shops/edit.html.erb
- app/views/shops/new.html.erb
- app/views/shops/show.html.erb
mudanças no front end
revisem, no que der conflito me falem
mas é pra tirar o banner e deixar o render com o link embaixo
> Changes banner

- app/controllers/products_controller.rb
- app/policies/product_policy.rb
acertei a autorização para só o dono do shop poder criar e editar um produto. podem validar?
@queirozcamila @patriciachedid
> Fix product policy

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
- app/views/shops/index.html.erb
> alteraçao no footer

- app/controllers/products_controller.rb
- app/views/products/new.html.erb
Pessoal, mudei o controller do produts pra conseguirmos adicionar os produtos que estavam dando erro. Verifiquem se foi
> Mudanças no controller do products

- app/views/shared/_navbar.html.erb
- db/schema.rb
adicionados os root_path nos links da navbar.
> Nav bar home link

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/products_controller.rb
- app/controllers/shops_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/shops/_info_window.html.erb
- db/schema.rb
> Geocode features

- app/assets/stylesheets/components/_cards.scss
- app/views/shops/index.html.erb
Incluí um link para adicionar uma nova loja e ajustei o texto no botão dos cartões. Não consegui ajustar o carrossel.
> Added button to create new shop and fixed buttons

- app/controllers/cart_products_controller.rb
- app/controllers/carts_controller.rb
- app/views/carts/show.html.erb
- app/views/shops/show.html.erb
- config/routes.rb
implementação do botão de compras e carrinho.
> Create cart product

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/components/navbar.js
- app/javascript/packs/application.js
- app/views/shared/_navbar.html.erb
- app/views/shops/index.html.erb
Pessoal, fiz algumas alterações no front da home-page.
> Adding some scss on home page

- app/controllers/cart_products_controller.rb
- app/views/shops/show.html.erb
coloquei as autorização nos botoes e mudei o redirect do botao de compras para ficar na loja
> insert authorize on shop show and redirect to shop after buy

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/shops/index.html.erb
Pessoal, fiz mais algumas alterações na home page - design. Aqui está tudo funcionando. Depois podem alterar qualquer coisa que não gostem porque mudei coisas no estilo. E ainda tem algumas coisas pra acertar.
> Adding new design changes on home page

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_index.scss
- app/models/shop.rb
- app/views/shared/_form.html.erb
- app/views/shops/new.html.erb
Fiz mudanças no visual do form (new shop) e traduzi. Ainda não descobri como traduzir o botão "browse" de foto.
> Made a new css for the form and translated it

- app/views/shops/show.html.erb
corrigido o link para o carrinho para ir para a ultima compra.
> fix link to send for last users cart

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_shopping.scss
- app/controllers/carts_controller.rb
- app/views/carts/show.html.erb
- app/views/shared/_cartshow.html.erb
front do carrinho com soma dos valores. podem validar?
@patriciachedid @queirozcamila
> make the cart visualization and style

- app/assets/stylesheets/components/_shopping.scss
- app/views/shared/_cartshow.html.erb
- app/views/shops/show.html.erb
inseri os produtos em cards como no index.
> Set shop show cards

- app/assets/stylesheets/components/_forms.scss
- app/views/shared/_form.html.erb
Adicionei um espaço no formulário para caber o botao e coloquei um border-radius bem leve
> adding height on form-shop-new

- app/views/shops/index.html.erb
- package.json
- yarn.lock
> fix shops carousel

- app/views/shops/index.html.erb
acertei o id para funcionar a rolagem e corrigi a quantidade de iterações para ficar sempre com 4 itens.
> Fix slide carousel

- app/assets/stylesheets/components/_buttons.scss
Só tirei o text decoration do botao. O nome da branch nao tem a ver com o feature, sorry people!
> Tirei o text-decoration do botao no index

- app/controllers/shops_controller.rb
- app/policies/product_policy.rb
- app/policies/shop_policy.rb
- app/views/shops/index.html.erb
- app/views/shops/show.html.erb
a pagina do shop não estava abrindo para não logado, coloquei para abrir mas não da para comprar. E acertei algumas condições para não logado para não quebrar o portal.
> fix authorizations logged or not

- app/controllers/shops_controller.rb
- app/javascript/plugins/init_mapbox.js
inseri o logo no map box e ajustei o tamanho. podem validar?
@patriciachedid @gustborges @queirozcamila
> Map box items

- app/assets/stylesheets/components/_buttons.scss
- app/views/shops/index.html.erb
- app/views/shops/show.html.erb
centralizei e adicionei um pouco de padding no botão.
tb coloquei mais um if no carrinho do shop-show, pq nao tinha lembrado de ter uma condição quando está logado mas nao tem carrinho ainda.
@gustborges @patriciachedid @queirozcamila
> Resize btn cards

- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/views/shared/_form.html.erb
- package.json
- yarn.lock
inseri o pacote para autocomplete do algolia e coloquei no form de new shop. podemos colocar no search na sequencia.
@gustborges @queirozcamila @patriciachedid
> insert autocomplete in new shop

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/shops/show.html.erb
Fiz as modificações para ficar responsivo, os cards não mudam de tamanho. passam para a proxima linha. Modifiquei os width para ficar com 4 cards por linha. coloquei um verde bemmm claro para background color e back color no card branco.
@gustborges @patriciachedid @queirozcamila
> Card responsive

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/newuser.scss
- app/controllers/application_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shops/new.html.erb
- config/routes.rb
> Navbarchanges

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_forms.scss
- app/views/shops/index.html.erb
Coloquei o botao ao lado do form e diminui o tamanho do mapa.
> Ajuste no tamanho do form e do mapa

- app/assets/stylesheets/components/_alert.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
Fiz algumas traduções de formulários e ajustei o alerta de senha errada, que aparecia no canto da página. Depois farei as traduções de alertas.
> Fixed the sign up alert for wrong password

- app/controllers/shops_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_geolocation.js
Ae Caio! Deixei o código comentado explicando e resolvendo nossas cabeçadas de quinta, auhauhuahuha
Tópicos relevantes para dar uma pesquisada depois:
- Ajax
- Rails.ujs, a biblioteca que substituiu o antigo jquery-ujs
- Callback function
Os links que usei para resolver:
- https://www.rubyguides.com/2019/03/rails-ajax/
- https://stackoverflow.com/questions/29500656/rails-ajax-request-not-setting-the-proper-request-type
Esse segundo é o que resolve a parte do formato que travamos no final da call, cheguei nele metendo um byebug dentro Shops#index e verificando request.format e depois request.format.to_s. E ví que tava "\*/\*". Daí pesquisei "ajax request arriving as \*/\*"
> Location filter

- app/views/devise/registrations/edit.html.erb
pessoal, tinha uma virgula fora de lugar em uma linha do user edit que tava quebrando o código. acertei la e traduzi o que tava faltando.
@gustborges @patriciachedid @queirozcamila
> Edit user view

- app/views/carts/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/products/index.html.erb
- app/views/shared/_cartshow.html.erb
- app/views/shops/show.html.erb
Traduzi alguns diálogos de confirmação
> Translated some dialogs and alerts

- app/assets/stylesheets/components/_cards.scss
- app/views/products/edit.html.erb
- app/views/shared/_form.html.erb
- app/views/shops/show.html.erb
Fiz uns ajustes no alinhamento dos cards
> Ajuste card

- app/assets/stylesheets/components/_alert.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- config/locales/devise.en.yml
> fIXED alerts

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/newuser.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Ajustei o tamanho do formulário, que estava muito estreito, arredondei bordas.
> Login beauty

- app/views/devise/registrations/edit.html.erb
- app/views/shared/_navbar.html.erb
inserida foto para avatar sem foto.
@patriciachedid
> avatar padrao para quem nao tem foto

- db/seeds.rb
> Fixed seed

- app/views/products/edit.html.erb
- app/views/products/new.html.erb
Traduzi os formulários de produto.
> Product new form

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/components/navbar.js
- app/javascript/packs/application.js
> adding js on navbar

- app/assets/stylesheets/components/_alert.scss
- app/views/carts/show.html.erb
> add alert to finish cart
